# Generated by Django 4.1 on 2022-09-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapspotmediaapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=55)),
                ('locationImg', models.CharField(max_length=55)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='snapspotmediaapi.driver')),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapspotmediaapi.location')),
                ('road_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapspotmediaapi.roadtype')),
            ],
        ),
    ]
