# Generated by Django 4.1 on 2022-09-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapspotmediaapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='locationId',
        ),
    ]
