# Generated by Django 4.1 on 2022-09-07 01:22

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('snapspotmediaapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='time_date',
            field=models.DateTimeField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
