# Generated by Django 4.1 on 2022-09-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapspotmediaapi', '0002_roadpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='userId',
            new_name='user',
        ),
    ]
