# Generated by Django 4.1 on 2022-09-08 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapspotmediaapi', '0003_alter_eventpost_time_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpost',
            name='time_date',
        ),
        migrations.AddField(
            model_name='eventpost',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
