# Generated by Django 4.1 on 2022-08-31 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapspotmediaapi', '0003_locationtype_locationid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=55)),
                ('locationImg', models.CharField(max_length=55)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='snapspotmediaapi.driver')),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapspotmediaapi.location')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapspotmediaapi.locationtype')),
            ],
        ),
    ]
